Proyecto/urls.py
from django.contrib import admin
from django.urls import path
from PreEntrega.views import (
                            mostrar_mis_tareas,
                            mostrar_personas, 
                            cargar_personas, 
                            BuscarPersonas,
                            mostrar_materias,
                            cargar_materias,
                            BuscarMaterias,
                            agregar_tarea,
                            BuscarTareas)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('mis-tareas', mostrar_mis_tareas, name="mis-tareas"),
    path('mis-tareas/agregar',agregar_tarea,name="tareas-agregar"),
    path('mis-tareas/list',BuscarTareas.as_view(),name="tareas-list"),
    path('personas', mostrar_personas, name="personas"),
    path('personas/create', cargar_personas,name="personas-create"),
    path('personas/list', BuscarPersonas.as_view(), name="personas-list"),
    path('materias/cargar', cargar_materias, name="materias-cargar"),
    path('materias/list', BuscarMaterias.as_view(),name="materias-list"),
    path('materias',mostrar_materias,name="materias"),
]

PreEntrega/models.py
from django.db import models

class Tarea(models.Model):
    tarea = models.TextField(max_length=100)
    lugar = models.TextField(max_length=100)

    def __str__(self):
        return f"{self.lugar} - {self.tarea}"
    
class Persona(models.Model):
    nombre = models.TextField(max_length=100)
    apellido = models.TextField(max_length=100)
    fecha_nacimiento = models.DateField()

    def __str__(self):
        return f"{self.id} - {self.nombre} - {self.apellido}"
    
class Materia(models.Model):
    nombre = models.TextField(max_length=100)
    año = models.TextField(max_length=100)

    def __str__(self):
        return f"{self.año}° - {self.nombre}"

PreEntrega/forms.py
from django import forms

class PersonaForm(forms.Form):
    nombre = forms.CharField(max_length=100)
    apellido = forms.CharField(max_length=100)
    fecha_nacimiento = forms.DateField()

class BuscarPersonasForm(forms.Form):
    criterio_nombre = forms.CharField(max_length=100)
    
class MateriaForm(forms.Form):
    nombre = forms.CharField(max_length=100)
    año = forms.CharField(max_length=100)

class BuscarMateriaForm(forms.Form):
    materias = forms.CharField(max_length=100)

class TareaForm(forms.Form):
    tarea = forms.CharField(max_length=100)
    lugar = forms.CharField(max_length=100)

class BuscarTareaForm(forms.Form):
    tarea = forms.CharField(max_length=100)

PreEntrega/views.py
from django.shortcuts import render
from PreEntrega.models import Tarea, Persona, Materia
from PreEntrega.forms import PersonaForm, BuscarPersonasForm, MateriaForm, BuscarMateriaForm, TareaForm, BuscarTareaForm
from django.views.generic import ListView

def mostrar_mis_tareas(request, criterio):
    if criterio == "todo":
        tareas = Tarea.objects.all()
    else:
        tareas = Tarea.objects.filter(nombre=criterio).all()

    return render(request, "PreEntrega/tareas.html", {"tareas": tareas})


def mostrar_personas(request):
    personas = Persona.objects.all()
    total_personas = len(personas)
    context = {
        "personas": personas,
        "total_personas":total_personas,
        "form": PersonaForm(),
    }
    return render(request, "PreEntrega/personas.html", context)

def cargar_personas(request):
    f = PersonaForm(request.POST)
    context = {
        "form": f
    }
    if f.is_valid():
        Persona(nombre=f.data["nombre"], apellido=f.data["apellido"], fecha_nacimiento=f.data["fecha_nacimiento"]).save()
        context['form'] = PersonaForm()

    context["personas"] = Persona.objects.all()
    context["total_personas"] = len(Persona.objects.all())
        
    
    return render(request, "PreEntrega/personas.html", context)

def mostrar_materias(request):
    materias = Materia.objects.all()
    context = {
        "materias": materias,
    }
    return render(request, "PreEntrega/materias.html", context)


def cargar_materias(request):
    f = MateriaForm(request.POST)
    context = {
        "form": f
    }
    if f.is_valid():
        Materia(nombre=f.data["nombre"], año=f.data["año"]).save()
        context['form'] = MateriaForm()

    context["materias"] = Materia.objects.all()
    return render(request, "PreEntrega/materias.html", context)

class BuscarPersonas(ListView):
    model = Persona
    context_object_name = "personas"

    def get_queryset(self):
        f = BuscarPersonasForm(self.request.GET)
        if f.is_valid():
            return Persona.objects.filter(nombre__icontains=f.data["criterio_nombre"]).all()
        return Persona.objects.none()
        

class BuscarMaterias(ListView):
    model = Materia
    context_object_name = "materias"
    
    def get_queryset(self):
        f = BuscarMateriaForm(self.request.GET)

        return Materia.objects.filter(nombre__icontains=f.data["materia"]).all()
    
def agregar_tarea(request):
    f = TareaForm(request.POST)
    context = {
        "form": f
    }
    if f.is_valid():
        Tarea(tarea=f.data["tarea"], lugar=f.data["lugar"]).save()
        context['form'] = TareaForm()

    context["tareas"] = Tarea.objects.all()
    return render(request, "PreEntrega/tareas.html", context)

class BuscarTareas(ListView):
    model = Tarea
    context_object_name = "tareas"
    
    def get_queryset(self):
        f = BuscarTareaForm(self.request.GET)
        if f.is_valid():
            return Tarea.objects.filter(tarea__icontains=f.data["tarea"]).all()
        return Tarea.objects.none()
        
        
        

PreEntrega/templates/PreEntrega/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block tittle %}{% endblock %}</title>
</head>
<body>
<h1>{% block titulo %} {%endblock%} </h1>
{% block listado %}
{% endblock %}

</body>
</html>

PreEntrega/templates/PreEntrega/materia_list.html
{% extends 'PreEntrega/base.html' %}
{% block title %} Materias {% endblock %}
{%block titulo%} Listas de Materias por año {%endblock%}

{% block listado %}

<form>
    <p>
        <label for="id_materia">Materia</label>
        <input type="text" name="materia" maxlength="100" required="" id="materia">

    </p>
    <p>
        <input type="submit" value="Buscar">
    </p>
</form>

<ul>
    {% for materia in materias %}
         <li>{{materia}} </li>
     {% endfor %}
</ul>
{% endblock %}

PreEntrega/templates/PreEntrega/materias.html
{% extends 'PreEntrega/base.html' %}

{%block titulo%} Listas de Materias por año {%endblock%}

{% block listado %}

<form action="{% url 'materias-cargar' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Agregar">

</form>
<ul>
    {% for materia in materias %}
         <li>{{materia}} </li>
     {% endfor %}
</ul>
{% endblock %}

{% block title %} Materias {% endblock %}

PreEntrega/templates/PreEntrega/persona_list.html
{% extends 'PreEntrega/base.html' %}

{%block titulo%} Listado de Personas {%endblock%}

{% block listado %}

<form>
    <p>
        <label for="id_criterio_nombre">Apellido</label>
        <input type="text" name="criterio_nombre" maxlength="100" required="" id="criterio_nombre">

    </p>
    <p>
        <input type="submit" value="Buscar">
    </p>
</form>

<ul>
    {% for persona in personas %}
         <li>{{persona}} </li>
     {% endfor %}
</ul>
{% endblock %}

{% block title %} Total Personas {{total_personas}} {% endblock %}

PreEntrega/templates/PreEntrega/personas.html
{% extends 'PreEntrega/base.html' %}

{%block titulo%} Listado de Personas {%endblock%}

{% block listado %}

<form action="{% url 'personas-create' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Agregar">

</form>

<ul>
    {% for persona in personas %}
         <li>{{persona}} </li>
     {% endfor %}
</ul>
{% endblock %}

{% block title %} Total Personas {{total_personas}} {% endblock %}

PreEntrega/templates/PreEntrega/tarea_list.html
{% extends 'PreEntrega/base.html' %}

{%block titulo%} Listado de Personas {%endblock%}

{% block listado %}

<form>
    <p>
        <label for="id_tarea">Tarea</label>
        <input type="text" name="tarea" maxlength="100" required="" id="tarea">

    </p>
    <p>
        <input type="submit" value="Buscar">
    </p>
</form>
<ul>
    {% for tarea in tareas %}
        <li>{{ tarea.tarea }} - {{ tarea.lugar }} </li>
    {% endfor %}
</ul>
{% endblock %}

{% block title %} Tareas {% endblock %}

PreEntrega/templates/PreEntrega/tareas.html
{% extends 'PreEntrega/base.html' %}

{%block titulo%} Listado de Tareas {%endblock%}

{% block listado %}

<form action="{% url 'tareas-agregar' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Agregar">

</form>
    <ul>
        {% for tarea in tareas %}
            <li>{{ tarea.tarea }} - {{ tarea.lugar }} </li>
        {% endfor %}
    </ul>
{% endblock %}

{% block title %} Tareas {% endblock %}